future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/
# relative_permalinks: true

# Setup
timezone:            Asia/Ho_Chi_Minh # eg. Asia/Kathmandu
locale:              en_us # eg. en_us
name:                Trung Ho
title:               leetrunghoo
tagline:             'tagline'
description:         'Software Developer - Music Lover'
url:                 
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_js: '/assets/js/'
icon:                /assets/imgages/logo.png
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 Trung Ho
  url:            	 www.leetrunghoo.com
  facebook:          leetrunghoo
  twitter:           leetrunghoo
  google_plus:       leetrunghoo
  linkedin:          trung-ho-quang-3a691797
  dribbble:          
  pinterest:         
  kiva:              

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml", "Gemfile", "Gemfile.lock"]
port:             	 4001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
