# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Analytics and webmaster tools stuff goes here
google_analytics:    UA-73537086-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:  

# Setup
timezone:            asia/hanoi # eg. Asia/Kathmandu
locale:              vi_VN # eg. en_us
name:                Trung Ho
title:               leetrunghoo
tagline:             'tagline'
description:         'Software Developer - Music Lover'
url:                 
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/img/posts/'
baseurl_featured_img: '/assets/img/hero/'
baseurl_featured_thumbnail: '/assets/img/thumbnail/'
baseurl_js:          '/assets/js/'
icon:                /assets/img/logo.png
disqus:              disqus_shortname # get it on https://disqus.com/admin/
gems:
  - jemoji

future:      true
# highlighter: rouge
# rouge:
#   css_class: 'highlight'
#   line_numbers: true

kramdown:
  input: GFM  # GitHub Flavored Markdown
  syntax_highlighter: rouge

author:
  name:              Trung Ho
  url:               www.leetrunghoo.com
  facebook:          leetrunghoo
  twitter:           leetrunghoo
  google_plus:       leetrunghoo
  linkedin:          trung-ho-quang-3a691797
  dribbble:          
  pinterest:         
  kiva:              

fb_admins:           leetrunghoo
fb_appid:            1053330601355734

# Server
exclude:             [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml", "Gemfile", "Gemfile.lock"]
port:                4001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
